name: Test lib3mf Installation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install_lib3mf_x64_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up vcpkg
        run: |
          git clone --recurse-submodules https://github.com/3MFConsortium/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install lib3mf
        run: |
          ./vcpkg/vcpkg install lib3mf:x64-linux --debug

  install_lib3mf_arm64_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up vcpkg
        run: |
          git clone --recurse-submodules https://github.com/3MFConsortium/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install lib3mf
        run: |
          ./vcpkg/vcpkg install lib3mf:arm64-linux --debug

  install_lib3mf_x86_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up vcpkg
        run: |
          git clone --recurse-submodules https://github.com/3MFConsortium/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install lib3mf
        run: |
          .\vcpkg\vcpkg install lib3mf:x86-windows --debug

  install_lib3mf_x64_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up vcpkg
        run: |
          git clone --recurse-submodules https://github.com/3MFConsortium/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install lib3mf
        run: |
          .\vcpkg\vcpkg install lib3mf:x64-windows --debug

  install_lib3mf_x64_windows_static:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up vcpkg
        run: |
          git clone --recurse-submodules https://github.com/3MFConsortium/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install lib3mf
        run: |
          .\vcpkg\vcpkg install lib3mf:x64-windows-static --debug

  install_lib3mf_arm64_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up vcpkg
        run: |
          git clone --recurse-submodules https://github.com/3MFConsortium/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install lib3mf
        run: |
          .\vcpkg\vcpkg install lib3mf:arm64-windows --debug

  install_lib3mf_x64_uwp:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up vcpkg
        run: |
          git clone --recurse-submodules https://github.com/3MFConsortium/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install lib3mf
        run: |
          .\vcpkg\vcpkg install lib3mf:x64-uwp --debug

  install_lib3mf_arm64_uwp:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up vcpkg
        run: |
          git clone --recurse-submodules https://github.com/3MFConsortium/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install lib3mf
        run: |
          .\vcpkg\vcpkg install lib3mf:arm64-uwp --debug

  install_lib3mf_x64_osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up vcpkg
        run: |
          git clone --recurse-submodules https://github.com/3MFConsortium/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install lib3mf
        run: |
          ./vcpkg/vcpkg install lib3mf:x64-osx --debug

  install_lib3mf_arm64_osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up vcpkg
        run: |
          git clone --recurse-submodules https://github.com/3MFConsortium/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install lib3mf
        run: |
          ./vcpkg/vcpkg install lib3mf:arm64-osx --debug